# Generated by Django 4.1.4 on 2023-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
