# Generated by Django 4.1.4 on 2023-01-12 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapui', '0005_alter_scrapitem_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapitem',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='phone number must be +91', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
